server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ibdp-analysis
    prefer-ip-address: true

spring:
  application:
    name: ibdp-analysis

info:
  app.name: ibdp
  build.artifactId: $project.artifactId$
  build.version: $project.version$


